call drop_table('USERS');

CREATE TABLE  USERS
   (	
    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   	"LOGIN" VARCHAR2(16 CHAR), 
	"NAME" VARCHAR2(50 CHAR), 
	"SURNAME" VARCHAR2(50 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
   );

CREATE UNIQUE INDEX "USERS_UNIQUE_UK" ON  "USERS" ("LOGIN");
