TRUNCATE  TABLE USER_ENTITY ;
INSERT INTO USER_ENTITY (ID, NAME) VALUES (1,'Francisco');
INSERT INTO USER_ENTITY (ID, NAME) VALUES (2,'José');
INSERT INTO USER_ENTITY (ID, NAME) VALUES (3,'Tomás');
INSERT INTO USER_ENTITY (ID, NAME) VALUES (4,'Flagelo');