CREATE TABLESPACE mmoreno_tb
  DATAFILE 'mmoreno_data.dbf'
  SIZE 20m;

CREATE USER MMORENO_OWN IDENTIFIED BY MMORENO_OWN
	DEFAULT TABLESPACE mmoreno_tb
	TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO MMORENO_OWN;

ALTER USER MMORENO_OWN QUOTA UNLIMITED ON mmoreno_tb;

GRANT CREATE TABLE TO MMORENO_OWN;
GRANT CREATE ANY TRIGGER TO MMORENO_OWN;
GRANT CREATE ANY PROCEDURE TO MMORENO_OWN;
GRANT DROP ANY TRIGGER TO MMORENO_OWN;
GRANT DROP ANY PROCEDURE TO MMORENO_OWN;
GRANT CREATE SEQUENCE TO MMORENO_OWN;